fooddash/urls.py
from django.urls import path

from . import views

app_name = 'fooddash'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), #/dashboard/
    path('add_recipe', views.AddRecipeView, name='add_recipe'), #/dashboard/add_recipe
    path('<int:pk>/delete/', views.DeleteRecipe.as_view(), name='recipe-delete'),
    path('<int:pk>/edit/', views.EditRecipe.as_view(), name='recipe-edit'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'), #/dashboard/5
    # path('<int:pk>/results', views.Resultsview.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('dashboard/', include('fooddash.urls')),
    path('admin/', admin.site.urls),
]

fooddash/models.py
import datetime

from django.db import models
from django.utils import timezone

class Recipes(models.Model):
    recipe_url = models.CharField(max_length=200)
    recipe_titel = models.CharField(max_length=200)
    recipe_img_url = models.CharField(max_length=200, default="https://www.takeoutlist.com/assets/images/food_default.png")
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.recipe_titel

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

fooddash/forms.py
from django import forms
from .models import Recipes
# class RecipeForm(forms.Form):
#     recipe_titel = forms.CharField(max_length=200)
#     recipe_url = forms.URLField()

class RecipeForm(forms.ModelForm):
    recipe_titel = forms.CharField(max_length=200)
    recipe_url = forms.URLField()
    class Meta:
        model = Recipes
        fields = ['recipe_titel', 'recipe_url']

# class PostForm(forms.ModelForm):
#     title = forms.CharField(max_length=128, help_text="plz enter")
#     views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
#     class Meta:
#         model = Post
#         fields = ['title', 'content', 'image', 'views', 'category']

fooddash/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.utils import timezone
from datetime import datetime
from .models import Recipes
from .forms import RecipeForm

from bs4 import BeautifulSoup
import requests
import logging

class IndexView(generic.ListView):
    template_name = 'fooddash/index.html'
    context_object_name = 'recipe_list'

    def get_queryset(self):
        """Return the last five publishd questions(not including future questions)."""
        return Recipes.objects.order_by('-pub_date')[:5]

def AddRecipeView(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        print(form)
        if form.is_valid():
            print(form.cleaned_data)
            data = form.cleaned_data

            ## Get url of image of the recipe
            with requests.get(data['recipe_url']) as r:
                soup = BeautifulSoup(r.content, features="lxml")
                title = soup.title
                img = soup.find(itemprop=["image", "photo"])
                print(img)
                if img:
                    img_url = img["src"]
                    rec = Recipes(
                            recipe_titel=data['recipe_titel'],
                            recipe_url=data['recipe_url'],
                            recipe_img_url=img_url,
                            pub_date=datetime.now(),
                        )
                else:
                    rec = Recipes(
                        recipe_titel=data['recipe_titel'],
                        recipe_url=data['recipe_url'],
                        pub_date=datetime.now(),
                    )
            rec.save()
            ## TODO: add picture url
            return redirect('fooddash:index')
    else:
        form = RecipeForm()

        return render(request, 'fooddash/add_recipe.html', {'form':form})

class DeleteRecipe(DeleteView):
    model = Recipes
    success_url = reverse_lazy('fooddash:index')

    # # TODO correctly implement this logic
    # rec = Recipes.objects.get(id=id)
    # rec.delete()
    # return redirect("fooddash:index")

class EditRecipe(UpdateView):
    model = Recipes
    form_class = RecipeForm
    template_name = "fooddash/add_recipe.html"

    def form_valid(self, form):
      self.object = form.save(commit=False)
      # Any manual settings go here
      self.object.save()
      return redirect('fooddash:index')

    def dispatch(self, request, *args, **kwargs):
        return super(EditRecipe, self).dispatch(request, *args, **kwargs)

    # ## TODO: correctly implement this
    # if request.method == 'POST':
    #     rec = Recipes.object.get(id=id)
    #     form = RecipeForm(instance=rec)

# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
#
#     def get_queryset(self):
#         """
#         Excludes any questiosn that aren't published yet.
#         """
#         return Question.objects.filter(pub_date__lte=timezone.now())
#
# class Resultsview(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

fooddash/templates/fooddash/add_recipe.html
<h1>Add Recipe here</h1>


<form action="{% url 'fooddash:add_recipe' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit">
</form>

<div>
  <a href="{% url 'fooddash:index' %}">
    <button type="button">Recipe list</button>
  </a>
</div>

fooddash/templates/fooddash/index.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'fooddash/style.css' %}">

<title>Recipe list</title>

<div class="container d-flex justify-content-center">
  <div class="row title_row text-center">
    <div class="col col-xs-3  col-xs-offset-4">
      <h1> Recipes:</h1>
    </div>
    <div class="col col-xs-1 add-recipe col-xs-offset-1">
      <a href="{% url 'fooddash:add_recipe' %}"><button type="button">Add recipe!</button></a>
    </div>
  </div>
  {% if recipe_list %}
      {% for recipe in recipe_list %}
        <div class="row recipe_row">
          <div class="col col-xs-7">
            <div class="row">
              <a class="recipe_titel" href={{recipe.recipe_url}}>{{ recipe.recipe_titel }}</a>
            </div>
            <div class="row">
              <div class="col col-xs-2">
                   <a href="{% url 'fooddash:recipe-edit' recipe.id %}""><button type="button">Edit</button></a>
              </div>
              <div class="col col-xs-2">
                <a href="{% url 'fooddash:recipe-delete' recipe.id %}""><button type="button">Delete</button></a>
              </div>
            </div>
          </div>

          <div class="col col-sm-1 col-xs-offset-2">
            <div class="">
              <img class=" recipe-img" src="{{ recipe.recipe_img_url }}" alt="recipe image">
            </div>
          </div>
        </div>
      {% endfor %}
  {% else %}
    <p> No Recipes are available.<p>
  {% endif %}
</div>

fooddash/templates/fooddash/recipes_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

fooddash/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong><p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
  <input = type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

fooddash/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p> No polls are available.<p>
{% endif %}

fooddash/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>